### ISSUE TITLE
Is there an example/guide of integration in a Django project?

### ISSUE THREAD

**Issue by eamigo86** [zitadel/example-api-python3-flask#4]
Hello,

I'm currently creating a test case using Zitadel with Django, but I can't find any documentation or guide on how to do it. This example is strongly tied to the use of Flask in its implementation.

Is there any doc, example, or tips to integrate Zitadel in a Django project?

Thanks in advance

**Comment by YetAnotherWebDeveloper** [comment]
I'd be interested in this as well!

**Comment by mffap** [comment]
@eamigo86 no not at the moment. Have you managed to solve it with Django? You might also want to post that question directly on the [zitadel/zitadel discussion](https://github.com/zitadel/zitadel/discussions). Maybe also someone from the [chat](https://zitadel.com/chat) has done it already.

**Comment by codespearhead** [comment]
Now [there is](https://zitadel.com/docs/examples/secure-api/python-django).

**Comment by mffap** [comment]
> Now [there is](https://zitadel.com/docs/examples/secure-api/python-django).

Yes. Thanks for pointing that out!
